services:
  postgres-db:
    image: postgres:15
    container_name: flora_db
    restart: always
    environment:
      POSTGRES_USER: flora_user
      POSTGRES_PASSWORD: flora_password
      POSTGRES_DB: flora_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flora_net

  redis-cache:
    image: redis:7-alpine
    container_name: flora_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flora_net

  backend:
    build: ./backend
    container_name: flora_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - flora_net
    depends_on:
      - postgres-db
      - redis-cache

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000/api
    container_name: flora_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - flora_net
    depends_on:
      - backend

  telegram-bot:
    build: ./telegram-bot
    container_name: flora_telegram_bot
    restart: always
    env_file:
      - ./telegram-bot/.env
    networks:
      - flora_net
    depends_on:
      - backend
      - redis-cache

volumes:
  postgres_data:
  redis_data:

networks:
  flora_net:
    driver: bridge